/**
 * This script generates UI modules for tools by running the Vite build.
 * It produces:
 * - src/ui/lib/tools/*.ts - One module per UI component containing bundled HTML
 * - src/ui/lib/loaders.ts - Lazy loaders for each UI module
 *
 * Because vite-plugin-singlefile requires a single entry point per build,
 * we run one Vite build per component (controlled via MCP_COMPONENT env var).
 * loaders.ts is generated here after all per-component builds complete.
 */

import { execSync } from "child_process";
import { join, dirname, resolve } from "path";
import { fileURLToPath } from "url";
import { readdirSync, existsSync, statSync, writeFileSync, mkdirSync, rmSync, readdir } from "fs";
import { promisify } from "util";

const readdirAsync = promisify(readdir);

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, "..", "..");

function toKebabCase(pascalCase: string): string {
    return pascalCase
        .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
        .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
        .toLowerCase();
}

function discoverComponents(): { name: string; toolName: string }[] {
    const componentsDir = resolve(rootDir, "src/ui/components");
    const result: { name: string; toolName: string }[] = [];

    for (const entry of readdirSync(componentsDir)) {
        const entryPath = join(componentsDir, entry);
        const indexPath = join(entryPath, "index.ts");

        if (statSync(entryPath).isDirectory() && existsSync(indexPath)) {
            result.push({ name: entry, toolName: toKebabCase(entry) });
        }
    }

    return result.sort((a, b) => a.name.localeCompare(b.name));
}

function writeLoadersFile(components: { name: string; toolName: string }[]): void {
    const generatedDir = resolve(rootDir, "src/ui/lib");
    mkdirSync(generatedDir, { recursive: true });

    const loaderEntries = components
        .map(
            ({ name, toolName }) =>
                `    "${toolName}": async () => {\n        const mod = await import("./tools/${toolName}.js");\n        return mod.${name}Html;\n    }`
        )
        .join(",\n");

    const loadersContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: pnpm generate:ui
 *
 * Lazy loaders for UI modules. Each loader returns a Promise<string> with the HTML.
 */
export const uiLoaders: Record<string, () => Promise<string>> = {
${loaderEntries}
};
`;
    writeFileSync(join(generatedDir, "loaders.ts"), loadersContent);
    console.log(
        `✓ loaders.ts written with ${components.length} loader(s): ${components.map((c) => c.toolName).join(", ")}`
    );
}

function pruneStaleToolFiles(components: { toolName: string }[]): void {
    const toolsDir = resolve(rootDir, "src/ui/lib/tools");
    if (!existsSync(toolsDir)) return;

    const currentToolNames = new Set(components.map((c) => c.toolName));
    for (const file of readdirSync(toolsDir)) {
        if (!file.endsWith(".ts")) continue;
        const toolName = file.replace(/\.ts$/, "");
        if (!currentToolNames.has(toolName)) {
            rmSync(join(toolsDir, file));
            console.log(`✓ Removed stale tool module: ${toolName}`);
        }
    }
}

export function generateUI(): void {
    const components = discoverComponents();
    console.log(`Building UI modules for ${components.length} component(s): ${components.map((c) => c.name).join(", ")}`);

    // Build each component in its own Vite process so viteSingleFile's
    // inlineDynamicImports works (it requires exactly one entry point).
    for (const { name } of components) {
        console.log(`\n[${name}] Building...`);
        execSync("vite build --config vite.ui.config.ts", {
            cwd: rootDir,
            stdio: "inherit",
            env: { ...process.env, MCP_COMPONENT: name },
        });
    }

    // After all per-component builds, write the combined loaders.ts
    writeLoadersFile(components);

    // Remove any stale tool modules from deleted components
    pruneStaleToolFiles(components);

    console.log("\n✓ UI modules generated");
}

// Run directly when executed as a script
if (import.meta.url === `file://${process.argv[1]}`) {
    generateUI();
}
